source "https://rubygems.org"

ruby "3.2.2"

gem "bootsnap", require: false
gem "faraday"
gem "pg"
gem "puma"
gem "rack-cors"
gem "rails", "~> 7.1.3", ">= 7.1.3.2"
gem "redis"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_bot_rails'
  gem 'faker'
end
